# Generated by Django 4.2.3 on 2023-07-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
